name: Build Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Make sure this job can be triggered manually

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/configure-pages@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          cd quaddtype/
          python -m pip install --upgrade pip
          python -m pip install "numpy @ git+https://github.com/numpy/numpy.git" pytest meson meson-python
      - name: Build quaddtype package
        run: |
          cd quaddtype/
          python -m pip install . -v
      - name: Build Sphinx documentation
        run: |
          cd quaddtype/
          python -m pip install ."[docs]"
          cd docs/
          sphinx-build -b html . _build/html/quaddtype
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './quaddtype/docs/_build/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
